#!/bin/csh
#------------------------------------------------------------------------------
#------------------------------------------------------------------------------
# @ N. Cardiel                                                 Version 19-12-97
#------------------------------------------------------------------------------
if ($3 == "") then
  echo " "
  echo "Usage: create_proas local_fortran local_c local_X11"
  echo " "
  echo "Example:"
  echo "% create_proas g77 gcc /usr/X11/lib       (linux)"
  echo "% create_proas f77 cc /usr/lib            (alpha)"
  echo " "
  echo "Note: local_fortran must be f77 or g77"
  echo "Note: local_c must be cc or gcc"
  echo " "
  exit
endif
#------------------------------------------------------------------------------
#------------------------------------------------------------------------------
if (($1 != "f77") && ($1 != "g77")) then
  echo "proas|ERROR> $1 is not a valid fortran compiler"
  exit
endif
if ($1 == "f77") then
  set local_fortran1 = 'f77 -c'
  set local_fortran2 = 'f77 -o'
#  set local_fortran1 = 'f77 -check_bounds -c'
#  set local_fortran2 = 'f77 -check_bounds -o'
endif
if ($1 == "g77") then
  set local_fortran1 = 'g77 -c'
  set local_fortran2 = 'g77 -o'
#  set local_fortran1 = 'g77 -Wall -c'
#  set local_fortran2 = 'g77 -Wall -o'
endif
#------------------------------------------------------------------------------
if (($2 != "cc") && ($2 != "gcc")) then
  echo "proas|ERROR> $2 is not a valid c compiler"
  exit
endif
if ($2 == "cc") then
  set local_c1 = 'cc -c'
  set local_c2 = 'cc -o'
endif
if ($2 == "gcc") then
  set local_c1 = 'gcc -Wall -c'
  set local_c2 = 'gcc -Wall -o'
endif
#------------------------------------------------------------------------------
if (-d $3) then
else
  echo "proas|ERROR> $3 is not a valid directory"
  exit
endif
set local_X11 = $3
#------------------------------------------------------------------------------
if($?PGPLOT_DIR)then
  echo "proas|INFO> PGLOT_DIR is set to "$PGPLOT_DIR
else
  echo "proas|ERROR> PGPLOT_DIR variable not defined"
  exit
endif
#------------------------------------------------------------------------------
#------------------------------------------------------------------------------
#                                                           Individual Programs
#------------------------------------------------------------------------------
#------------------------------------------------------------------------------
set fortran_files = `ls *.f`
echo "proas|programs> Total number of fortran files: " $#fortran_files
set next_file = 0
compila_files:
@ next_file = $next_file + 1
  if (-e `echo $fortran_files[$next_file]:r.o`) then
    rm -f `echo $fortran_files[$next_file]:r.o`
  endif
  echo "proas> "$local_fortran1 $fortran_files[$next_file]
  $local_fortran1 $fortran_files[$next_file]
  if (-e `echo $fortran_files[$next_file]:r.o`) then
  else
    echo " "
    echo -n "proas|ERROR> Error compiling file: "
    echo $fortran_files[$next_file]
    exit
  endif
  if ($next_file < $#fortran_files) goto compila_files
#------------------------------------------------------------------------------
set c_files = *.c
echo "proas|programs> Total number of C files: " $#c_files
set next_file = 0
compila_files:
@ next_file = $next_file + 1
  if (-e `echo $c_files[$next_file]:r.o`) then
    rm -f `echo $c_files[$next_file]:r.o`
  endif
  echo "proas> "$local_c1 $c_files[$next_file]
  $local_c1 $c_files[$next_file]
  if (-e `echo $c_files[$next_file]:r.o`) then
  else
    echo " "
    echo -n "proas|ERROR> Error compiling file: "
    echo $c_files[$next_file]
    exit
  endif
  if ($next_file < $#c_files) goto compila_files
#------------------------------------------------------------------------------
#------------------------------------------------------------------------------
echo -n "proas> "
echo "$local_fortran2 proas *.o -L$PGPLOT_DIR -L$local_X11 -lpgplot -lX11"
$local_fortran2 proas *.o -L$PGPLOT_DIR -L$local_X11 -lpgplot -lX11
if (-e proas) then
  rm -f *.o
else
  echo "proas|ERROR> Error compiling proas"
  echo " "
  exit
endif
#------------------------------------------------------------------------------
#------------------------------------------------------------------------------
echo " "
echo "proas|INFO> *********************************************************"
echo "proas|INFO> *********************************************************"
echo "proas|INFO>                 Installation completed"
echo "proas|INFO> *********************************************************"
echo "proas|INFO> *********************************************************"
echo " "
#------------------------------------------------------------------------------
#------------------------------------------------------------------------------
unset local_fortran1
unset local_fortran2
unset local_c1
unset local_c2
unset local_X11
unset local_file
unset fortran_files
unset c_files
unset next_file
#unset pausa_key
#------------------------------------------------------------------------------
#------------------------------------------------------------------------------
