C------------------------------------------------------------------------------
C------------------------------------------------------------------------------
        CHARACTER*255   READC               !read character
        INTEGER         READI               !read integer
        INTEGER         READILIM            !read integer inside a range
        REAL            READF               !read float
        INTEGER         TRUEBEG,TRUELEN     !character manipulation
C------------------------------------------------------------------------------
